### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by masx200** [svtslv/webdav-cli#4]
```shell
npx webdav-cli --username root --password root --host localhost --path d:/ --port 1905
```
```txt
                    _           _                                  _   _
 __      __   ___  | |__     __| |   __ _  __   __           ___  | | (_)
 \ \ /\ / /  / _ \ | '_ \   / _` |  / _` | \ \ / /  _____   / __| | | | |
  \ V  V /  |  __/ | |_) | | (_| | | (_| |  \ V /  |_____| | (__  | | | |
   \_/\_/    \___| |_.__/   \__,_|  \__,_|   \_/            \___| |_| |_|

Homepage: https://github.com/svtslv/webdav-cli

Server running at http://localhost:1905
[rights]: all
[digest]: false
username: root
password: root
Hit CTRL-C to stop the server
Run with --help to print help
_http_outgoing.js:543
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:543:11)
    at HTTPRequestContext.writeBody (C:\Users\ma\AppData\Local\Yarn\Data\global\node_modules\webdav-server\lib\server\v2\RequestContext.js:278:31)
    at done (C:\Users\ma\AppData\Local\Yarn\Data\global\node_modules\webdav-server\lib\server\v2\commands\Propfind.js:293:25)
    at C:\Users\ma\AppData\Local\Yarn\Data\global\node_modules\webdav-server\lib\server\v2\commands\Propfind.js:358:33
    at Workflow.err [as errorFn] (C:\Users\ma\AppData\Local\Yarn\Data\global\node_modules\webdav-server\lib\server\v2\commands\Propfind.js:320:33)
    at C:\Users\ma\AppData\Local\Yarn\Data\global\node_modules\webdav-server\lib\helper\Workflow.js:35:61
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

**Comment by masx200** [comment]
https://github.com/svtslv/webdav-cli/pull/3

**Comment by masx200** [comment]
request headers:
```txt
PROPFIND / HTTP/1.1
Host: localhost:1905
Connection: keep-alive
Authorization: Basic cm9vdDpyb290
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
cache-control: max-age=0
accept-language: zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6
upgrade-insecure-requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
Origin: http://localhost:1905
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:1905/
Accept-Encoding: gzip, deflate, br


```
response headers:
```txt
HTTP/1.1 200 OK
DAV: 1,2
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: DAV, content-length, Allow
MS-Author-Via: DAV
Server: webdav-server/2.6.2
WWW-Authenticate: Basic realm="Default realm"
Allow: PROPPATCH,PROPFIND,OPTIONS,DELETE,UNLOCK,COPY,LOCK,MOVE
Content-Type: text/html
Date: Mon, 31 Aug 2020 23:32:59 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 3660


```
response body:

```html
<a href="/">..</a><br/><a href="/$360RTLOG$">$360RTLOG$</a><br/><a href="/$RECYCLE.BIN">$RECYCLE.BIN</a><br/><a href="/-all-large-iso-esd">-all-large-iso-esd</a><br/><a href="/.freedownloadmanager">.freedownloadmanager</a><br/><a href="/.__deepin.db">.__deepin.db</a><br/><a href="/.__deepin.lft">.__deepin.lft</a><br/><a href="/.__deepin.num">.__deepin.num</a><br/><a href="/360Chrome">360Chrome</a><br/><a href="/360Downloads">360Downloads</a><br/><a href="/360PhoneInfo">360PhoneInfo</a><br/><a href="/360手机相册备份">360手机相册备份</a><br/><a href="/360极速浏览器下载">360极速浏览器下载</a><br/><a href="/360驱动大师目录">360驱动大师目录</a><br/><a href="/ApowersoftRecorderTemp">ApowersoftRecorderTemp</a><br/><a href="/aria2">aria2</a><br/><a href="/Autodesk">Autodesk</a><br/><a href="/BaiduNetdiskDownload">BaiduNetdiskDownload</a><br/><a href="/baidupandownload">baidupandownload</a><br/><a href="/BaiduYunDownload">BaiduYunDownload</a><br/><a href="/BOOT">BOOT</a><br/><a href="/CloudMusic">CloudMusic</a><br/><a href="/Desktop">Desktop</a><br/><a href="/Documents">Documents</a><br/><a href="/Downloads">Downloads</a><br/><a href="/DumpStack.log.tmp">DumpStack.log.tmp</a><br/><a href="/Everything">Everything</a><br/><a href="/Everything.zip">Everything.zip</a><br/><a href="/FeigeDownload">FeigeDownload</a><br/><a href="/FFOutput">FFOutput</a><br/><a href="/GameDownload">GameDownload</a><br/><a href="/GeePlayerDownload">GeePlayerDownload</a><br/><a href="/globdata.ini">globdata.ini</a><br/><a href="/heisha">heisha</a><br/><a href="/install.exe">install.exe</a><br/><a href="/install.ini">install.ini</a><br/><a href="/Intel">Intel</a><br/><a href="/kinggsoft">kinggsoft</a><br/><a href="/mongodb">mongodb</a><br/><a href="/Music">Music</a><br/><a href="/MyDrivers">MyDrivers</a><br/><a href="/PECMDx64.EXE">PECMDx64.EXE</a><br/><a href="/pecmd批量加载驱动.bat">pecmd批量加载驱动.bat</a><br/><a href="/pecmd批量加载驱动.txt">pecmd批量加载驱动.txt</a><br/><a href="/Pictures">Pictures</a><br/><a href="/Program Files">Program Files</a><br/><a href="/QQDownload">QQDownload</a><br/><a href="/QQMusicCache">QQMusicCache</a><br/><a href="/qqpcmgr_docpro">qqpcmgr_docpro</a><br/><a href="/qycache">qycache</a><br/><a href="/Recovery">Recovery</a><br/><a href="/RmDownloads">RmDownloads</a><br/><a href="/System Volume Information">System Volume Information</a><br/><a href="/TDDownload">TDDownload</a><br/><a href="/Users">Users</a><br/><a href="/USMISO">USMISO</a><br/><a href="/USM_TOOL">USM_TOOL</a><br/><a href="/vcredist.bmp">vcredist.bmp</a><br/><a href="/VC_RED.cab">VC_RED.cab</a><br/><a href="/VC_RED.MSI">VC_RED.MSI</a><br/><a href="/videos">videos</a><br/><a href="/WeGame">WeGame</a><br/><a href="/win32-loader">win32-loader</a><br/><a href="/WinRAR">WinRAR</a><br/><a href="/WinRAR.zip">WinRAR.zip</a><br/><a href="/XMPCache">XMPCache</a><br/><a href="/YunDownload 2.0.3">YunDownload 2.0.3</a><br/><a href="/YunGameBox">YunGameBox</a><br/><a href="/串口rs232转usb驱动">串口rs232转usb驱动</a><br/><a href="/串口rs232转usb驱动.7z">串口rs232转usb驱动.7z</a><br/><a href="/录音啦">录音啦</a><br/><a href="/我的下载">我的下载</a><br/><a href="/我的应用">我的应用</a><br/><a href="/我的驱动备份">我的驱动备份</a><br/><a href="/截图winsnap">截图winsnap</a><br/><a href="/花密flowerpassword.exe">花密flowerpassword.exe</a><br/><a href="/花密网页版-20190402-完善修改版-响应式的导航栏">花密网页版-20190402-完善修改版-响应式的导航栏</a><br/><a href="/迅雷下载">迅雷下载</a><br/>
```

**Comment by svtslv** [comment]
Fixed
